1. I/O = 對話機器人、本地端 =  網頁、資料庫
* User control, plot to control operating
* Predict Sales based on historical data

## Python for internal control
### Target: Time update budget, cost allocated for each object, target sales.

* Film: VIESHOW CINEMAS
* Period: one month
* Renewed for each operating activity


* Profit = Net income(NI) = (Revenue(REV)- Expense(EXP))*(1-Tax rate)
<br><br>
    * Income before income tax = Revenue - Expense
<br><br>
    * Revenue = Sales of ticket(Sales_T) + Sales of snake(Sales_SN) + Sales of beverage(Sales_BEV)
        1. Sales of ticket =  Ticket Price(Price_T)* Sales Volume of Ticket(VOL_T)
            * 3 sorts of ticket Price= {A box: 500; B box: 300; C box: 200}
        * Sales of snake = Snake Price* Sales Volume of Snake(VOL_SN)
            * 1 kind of snake= {Popcorn: 70}
        * Sales of beverage = Beverage Price* Sales Volume of Beverage(VOL_BEV)
            * 1 brand of beverage= {Coke: 50}
<br>    
    * Expense = Variable cost + Fixed cost
        1. Variable cost = Material(Mat) + Outsource cleaning Variable part (VC_OC)
            1. Material = Snake(M_SN) + Beverage(M_BEV)
                * Cost of snake = Snake Expense* Sales Volume of Snake 
                    * M_SN = EXP_SN* SV_SN
                * Cost of beverage = Beverage Expence* Sales Volume of Beverage
                    * M_BEV = EXP_BVE* SV_BVE
            * Outsource cleaning = {box A: 70/ ticket; box B: 50/ ticket; box C: 30/ ticket}
<br><br>            
        * Fixed cost = Labor cost(LC) + Overhead(OH)
            1. Labor cost = Parttime wages(LC_PT) + Management salaries(LC_MGT)
                * Parttime wages = Wages x hours = PT_wage x PT_hrs
                * Management salaries = Salary x positions = MGT_wage x MGT_num

            * Overhead = Movie Licence(OH_LIC) + Repairment(OH_REP) + Outsource cleaning Fixed part (OH_OC) + Rent(OH_RENT)

                1. Movie Licence: key in = default= 500000
                * Repairment: key in, default= 3000
                * Outsource cleaning: key in, default= 3000
                * Rent: key in, default= 500000
<br><br>            
    * Outsource Cleaning Expense
        * 3000 basic payment for each month
        * each box used calculate different extra expense

* Profit = (Revenue(REV)- Expense(EXP))*(1-Tax rate) 
    * $\Rightarrow Profit/(1-r) = REV - EXP$
    * $\Rightarrow Profit/(1-r) = REV - EXP = \Sigma (Price_i(P_i)- VariableCost_i(VC_i))* Sales Volumn_i(SV_i) - Fixed Cost(FC)$
    * $\because GM = P_i- VC_i$
    * $\Rightarrow Profit/(1-r) = REV - EXP = \sum ^{3}_{i=1} (GM_i* SV_i) - FC$ 
    * $\because Gross Margin Rate(GMR) = \dfrac {P_i- VC_i}{P_i}$
    * $\Rightarrow Profit/(1-r) = REV - EXP = \sum ^{3}_{i=1} (GMR_i* SalesRevenue_i(SR_i)) - FC$
<br><br>
* $Budget$: planned sales volumes and revenues, resource quantities and costs.
    * Sales Volume(SV); Sales Volume per Day(SVD)
        * Budget Sales Volume(Budget_SV); Budget Sales Volume per day(Budget_SVD)
        * Real Sales Volume(SV); SVD
    <br><br>
    * Profit/(1-r)+ EXP = $\sum ^{3}_{i=1} GMR_i* SV_i$
    * $\dfrac {Profit/(1-r) + EXP}{Operating Days}$ = Budget Revenue per day(Budget_REVD) = $\sum ^{3}_{i=1} GRM_i* BudgetSVD_i$
    * $\Rightarrow$ $\dfrac {BudgetREVD_i}{GRM_i}= BudgetSVD_i$
    
#### As real sales volume fluctuate, the budget sales volume per day will be adjusted followed the $\Delta Sales Volume$. We can expect the real sales in different $price$ and $quality$ of product based on the historical data. Cooperating with timely update database, managers can monitor the cash flow and underatand the operating condition. Therefore, managers can update marketing, pricing and purchasing strategies.

## I/O

In [114]:
# account = open('VIESHOW_Account.txt', 'w')

## Record time

In [1]:
#import package
from datetime import datetime
import calendar

In [2]:
#Date
now_date = datetime.now()
#Days in this month
DITM = calendar.monthrange(now_date.year,now_date.month)[1]

In [43]:
#Key in record
file_record = 'The {1} is {0:%d}, the {2} is {0:%B}, the {3} is {0:%I:%M%p}.'.format(now_date, "day", "month", "time")
time_record = '{0:%B %d %I:%M%p, }'.format(now_date, "day", "month", "time")

## Setting before operation

In [4]:
# print("請輸入貴公司詳細資訊。")

# #Target Net income in this month
# Profit = int(input('本月目標獲利?'))

# ##Revenue
# #Ticket price in each box
# print("請輸入營業項目相關資訊。")
# box_A = int(input('請問A廳票價?'))
# box_B = int(input('請問B廳票價?'))
# box_C = int(input('請問C廳票價?'))
# P_T = [box_A,box_B, box_C]

# ##Cost
# #Movies LIC
# OH_LIC = int(input('本月總計攤銷影片授權金?'))

# #Labor cost:{LC_PT; LC_MGT}
# PT_wage = int(input('法定最低薪資是?'))
# PT_hrs = int(input('本月兼職人員總工作時數?'))
# LC_PT = PT_wage* PT_hrs

# MGT_wage = int(input('管理階層本月薪資?'))
# MGT_num = int(input('管理層級人數?'))
# LC_MGT = MGT_wage* MGT_num

# #Overhead
# OH_Rent = int(input('本月電影院租金?'))
# OH_Repair = int(input('本月維修費用?'))

## Default , Labor cost, Overhead

In [5]:
import numpy as np

In [15]:
REV = 0
EXP = 0
SV = SV_T = SV_SN = SV_BER = 0
r = 0.4
#Movies on air
Movie = ["與神同行：最終審判", "不可能的任務 : 全面瓦解", "尖叫旅社 3：怪獸假期", "超人特攻隊 2"]
#Available boxes, snake
Box = ["A廳", "B廳", "C廳"]
Snake = ["Popcorn"]
Beverage = ["Coke"]
#Profit = Net income
Profit = 500000
#Pricing
box_A, box_B, box_C = 320, 270, 250
P_T = np.array([box_A,box_B, box_C])
Popcorn = 70
P_SN = np.array([Popcorn])
Coke = 50
P_BEV = np.array([Coke])
##Cost
#Movies LIC
OH_LIC = 500000
#Labor cost:{LC_PT; LC_MGT}
PT_wage = 133 
PT_hrs = 720
LC_PT = PT_wage*PT_hrs

MGT_wage = 50000
MGT_num = 5
LC_MGT = MGT_wage*MGT_num
LC = LC_PT+ LC_MGT
#Overhead
OH_Rent = 500000
OH_Repair = 3000
OH_OC = 3000
OH = OH_LIC+ OH_Rent+ OH_Repair+ OH_OC

### Expense

In [20]:
# Fixed cost = Labor cost(LC) + Overhead(OH)
FC = LC+ OH
# Variable cost= Material + Outsource cleaning(Variable part)
# Outsource cleaning = {box A: 70/ ticket; box B: 50/ ticket; box C: 30/ ticket} 
OC_A, OC_B, OC_C = 70, 50, 30
VC_OC = np.array([OC_A, OC_B, OC_C])
M_Popcorn = 20
VC_SN = np.array([M_Popcorn])
M_Coke = 15
VC_BEV = np.array([M_Coke])

### Gross margin

In [21]:
GM_box, GM_SN, GM_BEV = P_T-VC_OC, P_SN-VC_SN, P_BEV-VC_BEV
GMR_box, GMR_SN, GMR_BEV= GM_box/P_T, GM_SN/P_SN, GM_BEV/P_BEV

In [35]:
GMR_box, GMR_SN, GMR_BEV

(array([ 0.78125   ,  0.81481481,  0.88      ]),
 array([ 0.71428571]),
 array([ 0.7]))

## Budget

In [34]:
Profit/(1-r)+EXP +FC

2185093.3333333335

In [30]:
#Budget_Revenue_Per_Day
Budget_REVD = (Profit/(1-r)+EXP)/DITM
print("本月每日營業額目標為 %f元。" %Budget_REVD)

本月每日營業額目標為 26881.720430元。


## Update after each operating activity is recorded.

### Setting Movie

In [22]:
#Choose the movie | Movie_num
print('目前上映的電影有:')
print('1.與神同行：最終審判; 2.不可能的任務 : 全面瓦解; 3.尖叫旅社 3：怪獸假期')
print('請輸入電影代碼。')
Movie_reply = input()
if any(i in Movie_reply for i in("1", "一", "ne")):
    Movie_num = 0
    a = Movie[Movie_num]
    print('輸入%s'%a)
elif any(i in Movie_reply for i in("2", "二", "wo" ,"WO")):
    Movie_num = 1
    a = Movie[Movie_num]
    print('輸入%s'%a)
elif any(i in Movie_reply for i in("3", "三", "hree", "HREE")):
    Movie_num = 2
    a = Movie[Movie_num]
    print('輸入%s'%a)
else:
    print('404')

目前上映的電影有:
1.與神同行：最終審判; 2.不可能的任務 : 全面瓦解; 3.尖叫旅社 3：怪獸假期
請輸入電影代碼。
1
輸入與神同行：最終審判


### Setting box

In [23]:
#Choose the box | Box_num
print('今日開放的影廳有:')
print('1.A廳; 2.B廳; 3.C廳')
print('請輸入影廳代碼。')

box_reply = input()

if any(j in box_reply for j in("A", "1", "一", "ne", "NE")):
    Box_num = 0
    b = Box[Box_num]
    print('輸入%s'%b)
elif any(j in box_reply for j in("B", "2", "二", "wo", "WO")):
    Box_num = 1
    b = Box[Box_num]
    print('輸入%s'%b)
elif any(j in box_reply for j in("C", "3", "三", "hree", "HREE")):
    Box_num = 2
    b = Box[Box_num]
    print('輸入%s'%b)
else:
    print('404')

今日開放的影廳有:
1.A廳; 2.B廳; 3.C廳
請輸入影廳代碼。
2
輸入B廳


### Target Sales Volume and Sales Revenue

In [29]:
#Target Sales Volume for each operating activity
TSV_T = [0, 0, 0]
TSV_SN = [0]
TSV_BEV = [0]
TSR_T = TSR_SN = TSR_BEV = np.array([0,0,0])
#Target Sales Revenue for each operating activity

TSR_T[Box_num] = TSV_T[Box_num]*P_T[Box_num]
#As the Snake and Beverage have only one product, default setting as 0.
TSR_SN[0] = TSV_SN[0]*P_SN[0]
TSR_BEV[0] = TSV_BEV[0]*P_BEV[0]

### Real Sales Volume

In [52]:
#Ticket sales volume
SV_T = int(input("請問在"+ time_record+ b+ "播放的"+ a+ "賣出幾張票?"))
print("輸入賣出"+ b+ "播放的"+ a+ "%.f張票。"%SV_T)

SV_SN = int(input("請問在"+ time_record+ b+ "播放的"+ a+ "賣出幾份"+ Snake[0]+"?"))
print("輸入賣出"+ b+ "播放的"+ a+ "%.f份"%SV_SN+ Snake[0]+ "。")

SV_BER = int(input("請問在"+ time_record+ b+ "播放的"+ a+"賣出幾杯%s?"%Beverage[0]))
print("輸入賣出"+ b+ "播放的"+ a+ "%.f杯"%SV_BER+ Beverage[0]+ "。")

請問在August 16 12:59PM, B廳播放的與神同行：最終審判賣出幾張票?500
輸入賣出B廳播放的與神同行：最終審判500張票。
請問在August 16 12:59PM, B廳播放的與神同行：最終審判賣出幾份Popcorn?200
輸入賣出B廳播放的與神同行：最終審判200份Popcorn。
請問在August 16 12:59PM, B廳播放的與神同行：最終審判賣出幾杯Coke?300
輸入賣出B廳播放的與神同行：最終審判300杯Coke。


### Real Sales Revenus

In [53]:
SR_T = SV_T*GM_box
SR_SN = SV_SN*GM_SN
SR_BER = SV_BER*GM_BEV

In [54]:
SR_T, SR_SN, SR_BER

(array([125000, 110000, 110000]), array([10000]), array([10500]))